#!/bin/sh

echo "cleaning `pwd` ..."
echo -n "type [OK] to confirm: "
read answer
case $answer in
  OK)
    ;;
  *)
    echo 'abort'
    exit 2
    ;;
esac

rm README.md LICENSE setup
rm -rf .git/

gem install bundler
bundle install --path vendor/bundle

echo 'now git repo is not initialized!'
echo 'run git init to initialize'
