#!/bin/sh

echo "cleaning `pwd` ..."
echo -n "type [OK] to confirm: "
read answer
case $answer in
  OK)
    ;;
  *)
    echo 'abort'
    exit 2
    ;;
esac

echo "exec: removing needless files ..."
rm README.md LICENSE setup
rm -rf .git/

if ! hash bundle &>/dev/null ; then
  echo "exec: gem install bundler"
  gem install bundler
fi

echo "exec: bundle install --path vendor/bundle"
bundle install --path vendor/bundle

echo 'now git repo is not initialized!'
echo 'run git init to initialize'
